### PR TITLE
packages: Add brightnessctl and berry

### PR DESCRIPTION
**Pull request by owl4ce**
Add new package, `brightnessctl`

2021-04-01-190129_1920x1080_scrot

**Works like a charm!**

### CODE REVIEW

**Comment by protonesso** [comment]
Nice to utils section

**Comment by protonesso** [comment]
Move*

**Comment by protonesso** [comment]
But otherwise lgtm

**Comment by owl4ce** [comment]
done. wtf I forgot the letter l in the commit message

**Comment by owl4ce** [comment]
Added berry window manager

2021-04-01-200606_1920x1080_scrot

**Pull request merged**
