### PR TITLE
Already created directory

### PR DESCRIPTION
**Pull request by firasuke**

### CODE REVIEW

**Comment by protonesso** [comment]
Okay test it

**Comment by firasuke** [comment]
Test it? You mean this line isn't working?

```Shell
install -dm755 "$PKG"/{etc,usr/lib}/{depmod,modprobe}.d
```

**Comment by protonesso** [comment]
Yep

Firas Khalil Khana <notifications@github.com> schrieb am Di., 28. Apr.
2020, 15:19:

**Comment by firasuke** [comment]
Weird lol...

Ok closing.

**Pull request closed without merging**
