### PR TITLE
Attempt to package Lynx (Fixed)

### PR DESCRIPTION
**Pull request by ghost**
I left it in experimental, to be fixed. The naming of the file makes using $version and $release a bit awkward. 

https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/lynx (How Arch does it)
https://crux.nu/ports/crux-3.4/contrib/lynx/Pkgfile (For older 2.8.8 version)

### CODE REVIEW

**Comment by protonesso** [comment]
Check my school project repo

**Comment by ghost** [comment]
Curly brackets fix.

**Comment by ghost** [comment]
The one in the schoolproject repo does not separate version and release.

**Comment by ghost** [comment]
It's tested and now ready to pull.
Lynx

**Comment by protonesso** [comment]
Remove stuff for stripping

**Pull request merged**
